# golangci-lint configuration - ALL linters enabled
# This shows the COMPLETE picture of all code quality issues

version: 2

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters:
  # Enable ALL linters to see complete picture
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # All additional linters (alphabetically)
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint

  disable:
    # Only truly incompatible linters
    - ginkgolinter  # Not using Ginkgo
    - depguard     # Disabled: DNS server requires miekg/dns and all internal packages

linters-settings:
  # Minimal settings - don't hide any issues
  cyclop:
    max-complexity: 10
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 10
  funlen:
    lines: 60
    statements: 40
  lll:
    line-length: 120

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
  show-stats: true
